name: Generate CV

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'output/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'output/**'
      - '**.md'

# Add permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git push

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    # Install required dependencies for Puppeteer
    - name: Install Puppeteer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ca-certificates \
          fonts-liberation \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libcairo2 \
          libcups2 \
          libdbus-1-3 \
          libexpat1 \
          libfontconfig1 \
          libgbm1 \
          libglib2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrandr2 \
          libxrender1 \
          libxss1 \
          libxtst6 \
          xdg-utils

    - name: Install dependencies
      run: npm ci

    - name: Generate CV
      run: |
        mkdir -p output
        node index.js en
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

    - name: Upload CV artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv
        path: output/cv_en.pdf

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add output/cv_en.pdf
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update CV [skip ci]" && git push)
